services:
  app:
    build: ./
    tty: true
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      POSTGRES_USER: postgres
      APP_DATABASE_PASSWORD: password
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
